# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20170716_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': '校区', 'verbose_name_plural': '校区'},
        ),
        migrations.AlterModelOptions(
            name='classlist',
            options={'verbose_name': '班级列表', 'verbose_name_plural': '班级列表'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': '合同', 'verbose_name_plural': '合同'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程表', 'verbose_name_plural': '课程表'},
        ),
        migrations.AlterModelOptions(
            name='courserecord',
            options={'verbose_name': '上课记录', 'verbose_name_plural': '上课记录'},
        ),
        migrations.AlterModelOptions(
            name='customerfollowup',
            options={'verbose_name': '客户意向表', 'verbose_name_plural': '客户意向表'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': '已报名的课程', 'verbose_name_plural': '已报名的课程'},
        ),
        migrations.AlterModelOptions(
            name='paymentrecord',
            options={'verbose_name': '缴费记录', 'verbose_name_plural': '缴费记录'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色表', 'verbose_name_plural': '角色表'},
        ),
        migrations.AlterModelOptions(
            name='studyrecord',
            options={'verbose_name': '学习记录', 'verbose_name_plural': '学习记录'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='consult_courses',
            field=models.ManyToManyField(to='repository.Course', verbose_name='咨询的课程'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_consultant', to='repository.Account', verbose_name='接待人员'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮件'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='qq',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referral_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_referral', to='repository.Account', verbose_name='介绍人'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Source', verbose_name='客户来源'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weixin',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='微信'),
        ),
    ]
