# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20170717_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='电话'),
        ),
    ]
