# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20170717_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='qq',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weixin',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='微信'),
        ),
    ]
