# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20170720_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrecord',
            name='score',
            field=models.IntegerField(blank=True, choices=[(100, 'A+'), (90, 'A'), (85, 'B+'), (70, 'B'), (65, 'C+'), (60, 'C'), (40, 'C-'), (-50, 'D'), (0, 'N/A'), (-100, 'COPY')], null=True),
        ),
    ]
