# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20170720_2355'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studyrecord',
            unique_together=set([]),
        ),
    ]
