# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20170720_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aaa', to='repository.Account'),
        ),
    ]
